apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
  labels:
    app: renovate
spec:
  schedule: "@hourly"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: renovate
              image: renovate/renovate:41.135
              env:
                - name: RENOVATE_KUBERNETES
                  value: '{"fileMatch":[".*\\.ya?ml$"]}'
                - name: LOG_LEVEL
                  value: debug
              envFrom:
                - secretRef:
                    name: renovate-config
