apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-config
  namespace: renovate
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secrets-store
    kind: ClusterSecretStore
  target:
    name: renovate-config
  dataFrom:
    - extract:
        key: "renovate-config"
